;;; fq-packages-install --- Summary
;;; Commentary:
;;; Code:
(require 'init-el-get)
(el-get-bundle 2048.el)
(el-get-bundle color-theme)
(el-get-bundle color-theme-solarized)

;;(el-get-bundle auto-complete)
;;(el-get-bundle auto-complete-clang)
;;(el-get-bundle clang-complete-async)

(el-get-bundle emacs-w3m)
(el-get-bundle org-mode)
;;(el-get-bundle ecb)
(el-get-bundle emms)
(el-get-bundle evil)
(el-get-bundle flycheck)
(el-get-bundle highlight-symbol)
(el-get-bundle magit)
(el-get-bundle slime)
(el-get-bundle slim-mode)
(el-get-bundle smex)
(el-get-bundle yasnippet)
(el-get-bundle doxymacs)
(el-get-bundle google-c-style)
(el-get-bundle clang-format)
(el-get-bundle e2wm)
(el-get-bundle flex-mode)
(el-get-bundle bison-mode)
;;(el-get-bundle emacs-ycmd)

(el-get-bundle company-mode)
(el-get-bundle irony-mode)
(el-get-bundle company-irony)
(el-get-bundle flycheck-irony)
(el-get-bundle irony-eldoc)
(el-get-bundle slime-company)
(el-get-bundle company-c-headers)
(provide 'fq-packages-install)
;;; fq-packages-install ends here
