(package-install 'slime)
(package-install 'color-theme)
(package-install 'color-theme-solarized)
(package-install 'popup)
(package-install 'auto-complete)
(package-install 'auto-complete-clang)
(package-install 'yasnippet)
(package-install 'ecb)
(package-install 'mew)
(package-install 'w3m)
(package-install 'smex)
(package-install 'evil)
(package-install 'pcomplete-extension)
(package-install 'emms)
(package-install 'magit)
(package-install 'git)
(provide 'fq_package_install)

